### ISSUE TITLE
[Insight] PHP debug statements found - in app.php, line 13

### ISSUE THREAD

**Issue by azatyan** [php7-symfony-armenia/php-lessons#2]
**[in app.php, line 13](https://github.com/symfony-armenia/php-lessons/blob/1126538128defbae8a5862e5312e790499eabf6d/app.php#L13)**

> `var_dump()` should only be used for debug, and not committed to the source code repository.

```php


    $martin  = new Man('Martin', 'Elizbaryan', new \DateTime('29.04.1995'));


    var_dump($martin->getProfile());
    var_dump($martin);



```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/58996242-2c3e-4115-b2aa-dbd1b18f1027/analyses/1)_

**Comment by MartinElizbaryan** [comment]
I've done it
